# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/hpc/mosa004/mapclient-plugins/mapclientplugins.lungmodelstep/mapclientplugins/lungmodelstep/qt/lungmodelwidget.ui'
#
# Created: Tue Nov  6 18:34:09 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
# from PyQt5 import QtCore, QtGui, QtGui

class Ui_LungModelWidget(object):
    def setupUi(self, LungModelWidget):
        LungModelWidget.setObjectName("LungModelWidget")
        LungModelWidget.resize(865, 742)
        self.horizontalLayout = QtGui.QHBoxLayout(LungModelWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.controlPanel_groupBox = QtGui.QGroupBox(LungModelWidget)
        self.controlPanel_groupBox.setObjectName("controlPanel_groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.controlPanel_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.leftLung_groupBox = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.leftLung_groupBox.setObjectName("leftLung_groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.leftLung_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.leftlungUpper_checkBox = QtGui.QCheckBox(self.leftLung_groupBox)
        self.leftlungUpper_checkBox.setText("")
        self.leftlungUpper_checkBox.setObjectName("leftlungUpper_checkBox")
        self.gridLayout_4.addWidget(self.leftlungUpper_checkBox, 0, 1, 1, 1)
        self.leftlungLower = QtGui.QLabel(self.leftLung_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftlungLower.sizePolicy().hasHeightForWidth())
        self.leftlungLower.setSizePolicy(sizePolicy)
        self.leftlungLower.setObjectName("leftlungLower")
        self.gridLayout_4.addWidget(self.leftlungLower, 1, 0, 1, 1)
        self.leftlungLower_checkBox = QtGui.QCheckBox(self.leftLung_groupBox)
        self.leftlungLower_checkBox.setText("")
        self.leftlungLower_checkBox.setObjectName("leftlungLower_checkBox")
        self.gridLayout_4.addWidget(self.leftlungLower_checkBox, 1, 1, 1, 1)
        self.leftlungUpper = QtGui.QLabel(self.leftLung_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftlungUpper.sizePolicy().hasHeightForWidth())
        self.leftlungUpper.setSizePolicy(sizePolicy)
        self.leftlungUpper.setObjectName("leftlungUpper")
        self.gridLayout_4.addWidget(self.leftlungUpper, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.leftLung_groupBox)
        self.rightLung_groupBox = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.rightLung_groupBox.setObjectName("rightLung_groupBox")
        self.gridLayout_5 = QtGui.QGridLayout(self.rightLung_groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.rightlungLower_checkBox = QtGui.QCheckBox(self.rightLung_groupBox)
        self.rightlungLower_checkBox.setText("")
        self.rightlungLower_checkBox.setObjectName("rightlungLower_checkBox")
        self.gridLayout_5.addWidget(self.rightlungLower_checkBox, 2, 1, 1, 1)
        self.rightlungUpper = QtGui.QLabel(self.rightLung_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightlungUpper.sizePolicy().hasHeightForWidth())
        self.rightlungUpper.setSizePolicy(sizePolicy)
        self.rightlungUpper.setObjectName("rightlungUpper")
        self.gridLayout_5.addWidget(self.rightlungUpper, 0, 0, 1, 1)
        self.rightlungUpper_checkBox = QtGui.QCheckBox(self.rightLung_groupBox)
        self.rightlungUpper_checkBox.setText("")
        self.rightlungUpper_checkBox.setObjectName("rightlungUpper_checkBox")
        self.gridLayout_5.addWidget(self.rightlungUpper_checkBox, 0, 1, 1, 1)
        self.rightlungMiddle = QtGui.QLabel(self.rightLung_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightlungMiddle.sizePolicy().hasHeightForWidth())
        self.rightlungMiddle.setSizePolicy(sizePolicy)
        self.rightlungMiddle.setObjectName("rightlungMiddle")
        self.gridLayout_5.addWidget(self.rightlungMiddle, 1, 0, 1, 1)
        self.rightlungMiddle_checkBox = QtGui.QCheckBox(self.rightLung_groupBox)
        self.rightlungMiddle_checkBox.setText("")
        self.rightlungMiddle_checkBox.setObjectName("rightlungMiddle_checkBox")
        self.gridLayout_5.addWidget(self.rightlungMiddle_checkBox, 1, 1, 1, 1)
        self.rightlungLower = QtGui.QLabel(self.rightLung_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightlungLower.sizePolicy().hasHeightForWidth())
        self.rightlungLower.setSizePolicy(sizePolicy)
        self.rightlungLower.setObjectName("rightlungLower")
        self.gridLayout_5.addWidget(self.rightlungLower, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.rightLung_groupBox)
        self.morphing_groupBox = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.morphing_groupBox.setObjectName("morphing_groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.morphing_groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.modeThree_doubleSpinBox = QtGui.QDoubleSpinBox(self.morphing_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeThree_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.modeThree_doubleSpinBox.setSizePolicy(sizePolicy)
        self.modeThree_doubleSpinBox.setMinimum(-3.0)
        self.modeThree_doubleSpinBox.setMaximum(3.0)
        self.modeThree_doubleSpinBox.setSingleStep(0.1)
        self.modeThree_doubleSpinBox.setObjectName("modeThree_doubleSpinBox")
        self.gridLayout_2.addWidget(self.modeThree_doubleSpinBox, 2, 1, 1, 1)
        self.modeOne_label = QtGui.QLabel(self.morphing_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeOne_label.sizePolicy().hasHeightForWidth())
        self.modeOne_label.setSizePolicy(sizePolicy)
        self.modeOne_label.setObjectName("modeOne_label")
        self.gridLayout_2.addWidget(self.modeOne_label, 0, 0, 1, 1)
        self.modeFive_doubleSpinBox = QtGui.QDoubleSpinBox(self.morphing_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeFive_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.modeFive_doubleSpinBox.setSizePolicy(sizePolicy)
        self.modeFive_doubleSpinBox.setMinimum(-3.0)
        self.modeFive_doubleSpinBox.setMaximum(3.0)
        self.modeFive_doubleSpinBox.setSingleStep(0.1)
        self.modeFive_doubleSpinBox.setObjectName("modeFive_doubleSpinBox")
        self.gridLayout_2.addWidget(self.modeFive_doubleSpinBox, 4, 1, 1, 1)
        self.modeOne_doubleSpinBox = QtGui.QDoubleSpinBox(self.morphing_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeOne_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.modeOne_doubleSpinBox.setSizePolicy(sizePolicy)
        self.modeOne_doubleSpinBox.setMinimum(-3.0)
        self.modeOne_doubleSpinBox.setMaximum(3.0)
        self.modeOne_doubleSpinBox.setSingleStep(0.1)
        self.modeOne_doubleSpinBox.setObjectName("modeOne_doubleSpinBox")
        self.gridLayout_2.addWidget(self.modeOne_doubleSpinBox, 0, 1, 1, 1)
        self.modeTwo_label = QtGui.QLabel(self.morphing_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeTwo_label.sizePolicy().hasHeightForWidth())
        self.modeTwo_label.setSizePolicy(sizePolicy)
        self.modeTwo_label.setObjectName("modeTwo_label")
        self.gridLayout_2.addWidget(self.modeTwo_label, 0, 2, 1, 1)
        self.modeThree_label = QtGui.QLabel(self.morphing_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeThree_label.sizePolicy().hasHeightForWidth())
        self.modeThree_label.setSizePolicy(sizePolicy)
        self.modeThree_label.setObjectName("modeThree_label")
        self.gridLayout_2.addWidget(self.modeThree_label, 2, 0, 1, 1)
        self.modeFive_label = QtGui.QLabel(self.morphing_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeFive_label.sizePolicy().hasHeightForWidth())
        self.modeFive_label.setSizePolicy(sizePolicy)
        self.modeFive_label.setObjectName("modeFive_label")
        self.gridLayout_2.addWidget(self.modeFive_label, 4, 0, 1, 1)
        self.modeTwo_doubleSpinBox = QtGui.QDoubleSpinBox(self.morphing_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeTwo_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.modeTwo_doubleSpinBox.setSizePolicy(sizePolicy)
        self.modeTwo_doubleSpinBox.setMinimum(-3.0)
        self.modeTwo_doubleSpinBox.setMaximum(3.0)
        self.modeTwo_doubleSpinBox.setSingleStep(0.1)
        self.modeTwo_doubleSpinBox.setObjectName("modeTwo_doubleSpinBox")
        self.gridLayout_2.addWidget(self.modeTwo_doubleSpinBox, 0, 3, 1, 1)
        self.modeFour_label = QtGui.QLabel(self.morphing_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeFour_label.sizePolicy().hasHeightForWidth())
        self.modeFour_label.setSizePolicy(sizePolicy)
        self.modeFour_label.setObjectName("modeFour_label")
        self.gridLayout_2.addWidget(self.modeFour_label, 2, 2, 1, 1)
        self.modeFour_doubleSpinBox = QtGui.QDoubleSpinBox(self.morphing_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeFour_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.modeFour_doubleSpinBox.setSizePolicy(sizePolicy)
        self.modeFour_doubleSpinBox.setMinimum(-3.0)
        self.modeFour_doubleSpinBox.setMaximum(3.0)
        self.modeFour_doubleSpinBox.setSingleStep(0.1)
        self.modeFour_doubleSpinBox.setObjectName("modeFour_doubleSpinBox")
        self.gridLayout_2.addWidget(self.modeFour_doubleSpinBox, 2, 3, 1, 1)
        self.modeSix_label = QtGui.QLabel(self.morphing_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeSix_label.sizePolicy().hasHeightForWidth())
        self.modeSix_label.setSizePolicy(sizePolicy)
        self.modeSix_label.setObjectName("modeSix_label")
        self.gridLayout_2.addWidget(self.modeSix_label, 4, 2, 1, 1)
        self.modeSix_doubleSpinBox = QtGui.QDoubleSpinBox(self.morphing_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeSix_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.modeSix_doubleSpinBox.setSizePolicy(sizePolicy)
        self.modeSix_doubleSpinBox.setMinimum(-3.0)
        self.modeSix_doubleSpinBox.setMaximum(3.0)
        self.modeSix_doubleSpinBox.setSingleStep(0.1)
        self.modeSix_doubleSpinBox.setObjectName("modeSix_doubleSpinBox")
        self.gridLayout_2.addWidget(self.modeSix_doubleSpinBox, 4, 3, 1, 1)
        self.verticalLayout.addWidget(self.morphing_groupBox)
        self.reset_pushButton = QtGui.QPushButton(self.controlPanel_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_pushButton.sizePolicy().hasHeightForWidth())
        self.reset_pushButton.setSizePolicy(sizePolicy)
        self.reset_pushButton.setObjectName("reset_pushButton")
        self.verticalLayout.addWidget(self.reset_pushButton)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.exit_pushButton = QtGui.QPushButton(self.groupBox)
        self.exit_pushButton.setObjectName("exit_pushButton")
        self.horizontalLayout_3.addWidget(self.exit_pushButton)
        self.frame = QtGui.QFrame(self.groupBox)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtGui.QSpacerItem(120, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.frame)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout.addWidget(self.controlPanel_groupBox)
        self.sceneviewer_widget = SceneviewerWidget(LungModelWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneviewer_widget.sizePolicy().hasHeightForWidth())
        self.sceneviewer_widget.setSizePolicy(sizePolicy)
        self.sceneviewer_widget.setObjectName("sceneviewer_widget")
        self.horizontalLayout.addWidget(self.sceneviewer_widget)

        self.retranslateUi(LungModelWidget)
        QtCore.QMetaObject.connectSlotsByName(LungModelWidget)

    def retranslateUi(self, LungModelWidget):
        _translate = QtCore.QCoreApplication.translate
        LungModelWidget.setWindowTitle(_translate("LungModelWidget", "lungmodel"))
        self.controlPanel_groupBox.setTitle(_translate("LungModelWidget", "Control Panel"))
        self.leftLung_groupBox.setTitle(_translate("LungModelWidget", "Left lung"))
        self.leftlungLower.setText(_translate("LungModelWidget", "Lower lobe"))
        self.leftlungUpper.setText(_translate("LungModelWidget", "Upper lobe"))
        self.rightLung_groupBox.setTitle(_translate("LungModelWidget", "Right lung"))
        self.rightlungUpper.setText(_translate("LungModelWidget", "Upper lobe"))
        self.rightlungMiddle.setText(_translate("LungModelWidget", "Middle lobe"))
        self.rightlungLower.setText(_translate("LungModelWidget", "Lower lobe"))
        self.morphing_groupBox.setTitle(_translate("LungModelWidget", "Morph the lungs! "))
        self.modeOne_label.setText(_translate("LungModelWidget", "One"))
        self.modeTwo_label.setText(_translate("LungModelWidget", "Two"))
        self.modeThree_label.setText(_translate("LungModelWidget", "Three"))
        self.modeFive_label.setText(_translate("LungModelWidget", "Five"))
        self.modeFour_label.setText(_translate("LungModelWidget", "Four"))
        self.modeSix_label.setText(_translate("LungModelWidget", "Six"))
        self.reset_pushButton.setText(_translate("LungModelWidget", "Reset to Average model"))
        self.exit_pushButton.setText(_translate("LungModelWidget", "Exit"))

from opencmiss.zincwidgets.sceneviewerwidget import SceneviewerWidget
