# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/hpc/mosa004/mapclient-plugins/mapclientplugins.lungmodelstep/mapclientplugins/lungmodelstep/qt/lungmodelwidget.ui'
#
# Created: Tue Nov  6 18:34:09 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui


class Ui_LungModelWidget(object):
    def setupUi(self, LungModelWidget):
        LungModelWidget.setObjectName("LungModelWidget")
        LungModelWidget.resize(795, 627)
        self.horizontalLayout = QtGui.QHBoxLayout(LungModelWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.controlPanel_groupBox = QtGui.QGroupBox(LungModelWidget)
        self.controlPanel_groupBox.setObjectName("controlPanel_groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.controlPanel_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lung_groupBox = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.lung_groupBox.setObjectName("lung_groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.lung_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.leftlung_checkBox = QtGui.QCheckBox(self.lung_groupBox)
        self.leftlung_checkBox.setText("")
        self.leftlung_checkBox.setObjectName("leftlung_checkBox")
        self.gridLayout_4.addWidget(self.leftlung_checkBox, 0, 1, 1, 1)
        self.leftlung = QtGui.QLabel(self.lung_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftlung.sizePolicy().hasHeightForWidth())
        self.leftlung.setSizePolicy(sizePolicy)
        self.leftlung.setObjectName("leftlung")
        self.gridLayout_4.addWidget(self.leftlung, 0, 0, 1, 1)
        self.rightlung = QtGui.QLabel(self.lung_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightlung.sizePolicy().hasHeightForWidth())
        self.rightlung.setSizePolicy(sizePolicy)
        self.rightlung.setObjectName("rightlung")
        self.gridLayout_4.addWidget(self.rightlung, 1, 0, 1, 1)
        self.rightlung_checkBox = QtGui.QCheckBox(self.lung_groupBox)
        self.rightlung_checkBox.setText("")
        self.rightlung_checkBox.setObjectName("rightlung_checkBox")
        self.gridLayout_4.addWidget(self.rightlung_checkBox, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.lung_groupBox)
        self.component_groupBox = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.component_groupBox.setObjectName("component_groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.component_groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.component_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_2.setSizePolicy(sizePolicy)
        self.doubleSpinBox_2.setMinimum(-3.0)
        self.doubleSpinBox_2.setMaximum(3.0)
        self.doubleSpinBox_2.setSingleStep(0.1)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_2.addWidget(self.doubleSpinBox_2, 1, 1, 1, 1)
        self.modefour = QtGui.QLabel(self.component_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modefour.sizePolicy().hasHeightForWidth())
        self.modefour.setSizePolicy(sizePolicy)
        self.modefour.setObjectName("modefour")
        self.gridLayout_2.addWidget(self.modefour, 3, 0, 1, 1)
        self.modetwo = QtGui.QLabel(self.component_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modetwo.sizePolicy().hasHeightForWidth())
        self.modetwo.setSizePolicy(sizePolicy)
        self.modetwo.setObjectName("modetwo")
        self.gridLayout_2.addWidget(self.modetwo, 1, 0, 1, 1)
        self.modeone = QtGui.QLabel(self.component_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeone.sizePolicy().hasHeightForWidth())
        self.modeone.setSizePolicy(sizePolicy)
        self.modeone.setObjectName("modeone")
        self.gridLayout_2.addWidget(self.modeone, 0, 0, 1, 1)
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.component_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_5.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_5.setSizePolicy(sizePolicy)
        self.doubleSpinBox_5.setMinimum(-3.0)
        self.doubleSpinBox_5.setMaximum(3.0)
        self.doubleSpinBox_5.setSingleStep(0.1)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout_2.addWidget(self.doubleSpinBox_5, 4, 1, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.component_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy)
        self.doubleSpinBox.setMinimum(-3.0)
        self.doubleSpinBox.setMaximum(3.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_2.addWidget(self.doubleSpinBox, 0, 1, 1, 1)
        self.modethree = QtGui.QLabel(self.component_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modethree.sizePolicy().hasHeightForWidth())
        self.modethree.setSizePolicy(sizePolicy)
        self.modethree.setObjectName("modethree")
        self.gridLayout_2.addWidget(self.modethree, 2, 0, 1, 1)
        self.modefive = QtGui.QLabel(self.component_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modefive.sizePolicy().hasHeightForWidth())
        self.modefive.setSizePolicy(sizePolicy)
        self.modefive.setObjectName("modefive")
        self.gridLayout_2.addWidget(self.modefive, 4, 0, 1, 1)
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.component_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_4.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_4.setSizePolicy(sizePolicy)
        self.doubleSpinBox_4.setMinimum(-3.0)
        self.doubleSpinBox_4.setMaximum(3.0)
        self.doubleSpinBox_4.setSingleStep(0.1)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_2.addWidget(self.doubleSpinBox_4, 3, 1, 1, 1)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.component_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_3.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_3.setSizePolicy(sizePolicy)
        self.doubleSpinBox_3.setMinimum(-3.0)
        self.doubleSpinBox_3.setMaximum(3.0)
        self.doubleSpinBox_3.setSingleStep(0.1)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_2.addWidget(self.doubleSpinBox_3, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.component_groupBox)
        self.frame_2 = QtGui.QFrame(self.controlPanel_groupBox)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.morph_pushButton = QtGui.QPushButton(self.frame_2)
        self.morph_pushButton.setObjectName("morph_pushButton")
        self.horizontalLayout_5.addWidget(self.morph_pushButton)
        self.reset_pushButton = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_pushButton.sizePolicy().hasHeightForWidth())
        self.reset_pushButton.setSizePolicy(sizePolicy)
        self.reset_pushButton.setObjectName("reset_pushButton")
        self.horizontalLayout_5.addWidget(self.reset_pushButton)
        self.verticalLayout.addWidget(self.frame_2)
        self.groupBox_2 = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.breating = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.breating.sizePolicy().hasHeightForWidth())
        self.breating.setSizePolicy(sizePolicy)
        self.breating.setObjectName("breating")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.breating)
        self.breathing_checkBox = QtGui.QCheckBox(self.groupBox_2)
        self.breathing_checkBox.setText("")
        self.breathing_checkBox.setObjectName("breathing_checkBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.breathing_checkBox)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addWidget(self.groupBox)
        self.frame = QtGui.QFrame(self.controlPanel_groupBox)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.done_pushButton = QtGui.QPushButton(self.frame)
        self.done_pushButton.setObjectName("done_pushButton")
        self.horizontalLayout_2.addWidget(self.done_pushButton)
        spacerItem1 = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.controlPanel_groupBox)
        self.sceneviewer_widget = SceneviewerWidget(LungModelWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneviewer_widget.sizePolicy().hasHeightForWidth())
        self.sceneviewer_widget.setSizePolicy(sizePolicy)
        self.sceneviewer_widget.setObjectName("sceneviewer_widget")
        self.horizontalLayout.addWidget(self.sceneviewer_widget)

        self.retranslateUi(LungModelWidget)
        QtCore.QMetaObject.connectSlotsByName(LungModelWidget)

    def retranslateUi(self, LungModelWidget):
        LungModelWidget.setWindowTitle(QtGui.QApplication.translate("LungModelWidget", "Lung Model", None, QtGui.QApplication.UnicodeUTF8))
        self.controlPanel_groupBox.setTitle(QtGui.QApplication.translate("LungModelWidget", "Control Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.lung_groupBox.setTitle(QtGui.QApplication.translate("LungModelWidget", "Lung:", None, QtGui.QApplication.UnicodeUTF8))
        self.leftlung.setText(QtGui.QApplication.translate("LungModelWidget", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.rightlung.setText(QtGui.QApplication.translate("LungModelWidget", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.component_groupBox.setTitle(QtGui.QApplication.translate("LungModelWidget", "Components", None, QtGui.QApplication.UnicodeUTF8))
        self.modefour.setText(QtGui.QApplication.translate("LungModelWidget", "Four", None, QtGui.QApplication.UnicodeUTF8))
        self.modetwo.setText(QtGui.QApplication.translate("LungModelWidget", "Two", None, QtGui.QApplication.UnicodeUTF8))
        self.modeone.setText(QtGui.QApplication.translate("LungModelWidget", "One", None, QtGui.QApplication.UnicodeUTF8))
        self.modethree.setText(QtGui.QApplication.translate("LungModelWidget", "Three", None, QtGui.QApplication.UnicodeUTF8))
        self.modefive.setText(QtGui.QApplication.translate("LungModelWidget", "Five", None, QtGui.QApplication.UnicodeUTF8))
        self.morph_pushButton.setText(QtGui.QApplication.translate("LungModelWidget", "Morph it!", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_pushButton.setText(QtGui.QApplication.translate("LungModelWidget", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("LungModelWidget", "Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.breating.setText(QtGui.QApplication.translate("LungModelWidget", "Breathing", None, QtGui.QApplication.UnicodeUTF8))
        self.done_pushButton.setText(QtGui.QApplication.translate("LungModelWidget", "Exit", None, QtGui.QApplication.UnicodeUTF8))

from opencmiss.zincwidgets.sceneviewerwidget import SceneviewerWidget
