# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/hpc/mosa004/mapclient-plugins/mapclientplugins.lungmodelstep/mapclientplugins/lungmodelstep/qt/lungmodelwidget.ui'
#
# Created: Tue Nov  6 18:34:09 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui


class Ui_LungModelWidget(object):
    def setupUi(self, LungModelWidget):
        LungModelWidget.setObjectName("LungModelWidget")
        LungModelWidget.resize(795, 627)
        self.horizontalLayout = QtGui.QHBoxLayout(LungModelWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.controlPanel_groupBox = QtGui.QGroupBox(LungModelWidget)
        self.controlPanel_groupBox.setObjectName("controlPanel_groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.controlPanel_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.time_groupBox = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.time_groupBox.setObjectName("time_groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.time_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.timeLoop_checkBox_2 = QtGui.QCheckBox(self.time_groupBox)
        self.timeLoop_checkBox_2.setText("")
        self.timeLoop_checkBox_2.setObjectName("timeLoop_checkBox_2")
        self.gridLayout_4.addWidget(self.timeLoop_checkBox_2, 0, 1, 1, 1)
        self.timeValue_label = QtGui.QLabel(self.time_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeValue_label.sizePolicy().hasHeightForWidth())
        self.timeValue_label.setSizePolicy(sizePolicy)
        self.timeValue_label.setObjectName("timeValue_label")
        self.gridLayout_4.addWidget(self.timeValue_label, 0, 0, 1, 1)
        self.timeValue_label_2 = QtGui.QLabel(self.time_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeValue_label_2.sizePolicy().hasHeightForWidth())
        self.timeValue_label_2.setSizePolicy(sizePolicy)
        self.timeValue_label_2.setObjectName("timeValue_label_2")
        self.gridLayout_4.addWidget(self.timeValue_label_2, 1, 0, 1, 1)
        self.timeLoop_checkBox_3 = QtGui.QCheckBox(self.time_groupBox)
        self.timeLoop_checkBox_3.setText("")
        self.timeLoop_checkBox_3.setObjectName("timeLoop_checkBox_3")
        self.gridLayout_4.addWidget(self.timeLoop_checkBox_3, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.time_groupBox)
        self.video_groupBox = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.video_groupBox.setObjectName("video_groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.video_groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.video_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_2.setSizePolicy(sizePolicy)
        self.doubleSpinBox_2.setMinimum(-3.0)
        self.doubleSpinBox_2.setMaximum(3.0)
        self.doubleSpinBox_2.setSingleStep(0.1)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_2.addWidget(self.doubleSpinBox_2, 1, 1, 1, 1)
        self.framesPerSecond_label_2 = QtGui.QLabel(self.video_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framesPerSecond_label_2.sizePolicy().hasHeightForWidth())
        self.framesPerSecond_label_2.setSizePolicy(sizePolicy)
        self.framesPerSecond_label_2.setObjectName("framesPerSecond_label_2")
        self.gridLayout_2.addWidget(self.framesPerSecond_label_2, 3, 0, 1, 1)
        self.framesPerSecond_label = QtGui.QLabel(self.video_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framesPerSecond_label.sizePolicy().hasHeightForWidth())
        self.framesPerSecond_label.setSizePolicy(sizePolicy)
        self.framesPerSecond_label.setObjectName("framesPerSecond_label")
        self.gridLayout_2.addWidget(self.framesPerSecond_label, 1, 0, 1, 1)
        self.frameIndex_label = QtGui.QLabel(self.video_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameIndex_label.sizePolicy().hasHeightForWidth())
        self.frameIndex_label.setSizePolicy(sizePolicy)
        self.frameIndex_label.setObjectName("frameIndex_label")
        self.gridLayout_2.addWidget(self.frameIndex_label, 0, 0, 1, 1)
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.video_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_5.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_5.setSizePolicy(sizePolicy)
        self.doubleSpinBox_5.setMinimum(-3.0)
        self.doubleSpinBox_5.setMaximum(3.0)
        self.doubleSpinBox_5.setSingleStep(0.1)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout_2.addWidget(self.doubleSpinBox_5, 4, 1, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.video_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy)
        self.doubleSpinBox.setMinimum(-3.0)
        self.doubleSpinBox.setMaximum(3.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_2.addWidget(self.doubleSpinBox, 0, 1, 1, 1)
        self.frameIndex_label_2 = QtGui.QLabel(self.video_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameIndex_label_2.sizePolicy().hasHeightForWidth())
        self.frameIndex_label_2.setSizePolicy(sizePolicy)
        self.frameIndex_label_2.setObjectName("frameIndex_label_2")
        self.gridLayout_2.addWidget(self.frameIndex_label_2, 2, 0, 1, 1)
        self.framesPerSecond_label_3 = QtGui.QLabel(self.video_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framesPerSecond_label_3.sizePolicy().hasHeightForWidth())
        self.framesPerSecond_label_3.setSizePolicy(sizePolicy)
        self.framesPerSecond_label_3.setObjectName("framesPerSecond_label_3")
        self.gridLayout_2.addWidget(self.framesPerSecond_label_3, 4, 0, 1, 1)
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.video_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_4.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_4.setSizePolicy(sizePolicy)
        self.doubleSpinBox_4.setMinimum(-3.0)
        self.doubleSpinBox_4.setMaximum(3.0)
        self.doubleSpinBox_4.setSingleStep(0.1)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_2.addWidget(self.doubleSpinBox_4, 3, 1, 1, 1)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.video_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_3.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_3.setSizePolicy(sizePolicy)
        self.doubleSpinBox_3.setMinimum(-3.0)
        self.doubleSpinBox_3.setMaximum(3.0)
        self.doubleSpinBox_3.setSingleStep(0.1)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_2.addWidget(self.doubleSpinBox_3, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.video_groupBox)
        self.frame_2 = QtGui.QFrame(self.controlPanel_groupBox)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.done_pushButton_2 = QtGui.QPushButton(self.frame_2)
        self.done_pushButton_2.setObjectName("done_pushButton_2")
        self.horizontalLayout_5.addWidget(self.done_pushButton_2)
        self.defineROI_pushButton_4 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defineROI_pushButton_4.sizePolicy().hasHeightForWidth())
        self.defineROI_pushButton_4.setSizePolicy(sizePolicy)
        self.defineROI_pushButton_4.setObjectName("defineROI_pushButton_4")
        self.horizontalLayout_5.addWidget(self.defineROI_pushButton_4)
        self.verticalLayout.addWidget(self.frame_2)
        self.groupBox_2 = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.timeValue_label_3 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeValue_label_3.sizePolicy().hasHeightForWidth())
        self.timeValue_label_3.setSizePolicy(sizePolicy)
        self.timeValue_label_3.setObjectName("timeValue_label_3")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.timeValue_label_3)
        self.timeLoop_checkBox_4 = QtGui.QCheckBox(self.groupBox_2)
        self.timeLoop_checkBox_4.setText("")
        self.timeLoop_checkBox_4.setObjectName("timeLoop_checkBox_4")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.timeLoop_checkBox_4)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox = QtGui.QGroupBox(self.controlPanel_groupBox)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addWidget(self.groupBox)
        self.frame = QtGui.QFrame(self.controlPanel_groupBox)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.done_pushButton = QtGui.QPushButton(self.frame)
        self.done_pushButton.setObjectName("done_pushButton")
        self.horizontalLayout_2.addWidget(self.done_pushButton)
        spacerItem1 = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.controlPanel_groupBox)
        self.sceneviewer_widget = BaseSceneviewerWidget(LungModelWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneviewer_widget.sizePolicy().hasHeightForWidth())
        self.sceneviewer_widget.setSizePolicy(sizePolicy)
        self.sceneviewer_widget.setObjectName("sceneviewer_widget")
        self.horizontalLayout.addWidget(self.sceneviewer_widget)

        self.retranslateUi(LungModelWidget)
        QtCore.QMetaObject.connectSlotsByName(LungModelWidget)

    def retranslateUi(self, LungModelWidget):
        LungModelWidget.setWindowTitle(QtGui.QApplication.translate("LungModelWidget", "Image Based Fiducial Markers", None, QtGui.QApplication.UnicodeUTF8))
        self.controlPanel_groupBox.setTitle(QtGui.QApplication.translate("LungModelWidget", "Control Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.time_groupBox.setTitle(QtGui.QApplication.translate("LungModelWidget", "Lung:", None, QtGui.QApplication.UnicodeUTF8))
        self.timeValue_label.setText(QtGui.QApplication.translate("LungModelWidget", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.timeValue_label_2.setText(QtGui.QApplication.translate("LungModelWidget", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.video_groupBox.setTitle(QtGui.QApplication.translate("LungModelWidget", "Components", None, QtGui.QApplication.UnicodeUTF8))
        self.framesPerSecond_label_2.setText(QtGui.QApplication.translate("LungModelWidget", "Four", None, QtGui.QApplication.UnicodeUTF8))
        self.framesPerSecond_label.setText(QtGui.QApplication.translate("LungModelWidget", "Two", None, QtGui.QApplication.UnicodeUTF8))
        self.frameIndex_label.setText(QtGui.QApplication.translate("LungModelWidget", "One", None, QtGui.QApplication.UnicodeUTF8))
        self.frameIndex_label_2.setText(QtGui.QApplication.translate("LungModelWidget", "Three", None, QtGui.QApplication.UnicodeUTF8))
        self.framesPerSecond_label_3.setText(QtGui.QApplication.translate("LungModelWidget", "Five", None, QtGui.QApplication.UnicodeUTF8))
        self.done_pushButton_2.setText(QtGui.QApplication.translate("LungModelWidget", "Morph it!", None, QtGui.QApplication.UnicodeUTF8))
        self.defineROI_pushButton_4.setText(QtGui.QApplication.translate("LungModelWidget", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("LungModelWidget", "Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.timeValue_label_3.setText(QtGui.QApplication.translate("LungModelWidget", "Breathing", None, QtGui.QApplication.UnicodeUTF8))
        self.done_pushButton.setText(QtGui.QApplication.translate("LungModelWidget", "Exit", None, QtGui.QApplication.UnicodeUTF8))

from opencmiss.zincwidgets.basesceneviewerwidget import BaseSceneviewerWidget
